# Generated by Django 5.0.14 on 2025-07-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default='https://images.unsplash.com/photo-1526779259212-939e64788e3c?fm=jpg', max_length=2000),
            preserve_default=False,
        ),
    ]
